//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoOrganizer.UI.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoOrganizer.UI.Resources.Language.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual setting is: .
        /// </summary>
        public static string ActualSettingIs {
            get {
                return ResourceManager.GetString("ActualSettingIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Photos.
        /// </summary>
        public static string AddedPhotos {
            get {
                return ResourceManager.GetString("AddedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo....
        /// </summary>
        public static string AddPhoto_menu {
            get {
                return ResourceManager.GetString("AddPhoto_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to photo.
        /// </summary>
        public static string AddToPhoto {
            get {
                return ResourceManager.GetString("AddToPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to shelve.
        /// </summary>
        public static string AddToShelve {
            get {
                return ResourceManager.GetString("AddToShelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Photos.
        /// </summary>
        public static string AvailablePhotos {
            get {
                return ResourceManager.GetString("AvailablePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose folder for &apos;backup&apos;:.
        /// </summary>
        public static string ChooseFolder_windowTitle {
            get {
                return ResourceManager.GetString("ChooseFolder_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve made changes. Do you really want to close this item?.
        /// </summary>
        public static string CloseConfirmation_message {
            get {
                return ResourceManager.GetString("CloseConfirmation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Open Tabs.
        /// </summary>
        public static string CloseOpenTabs_menu {
            get {
                return ResourceManager.GetString("CloseOpenTabs_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will erase all previous data from Database. Are you sure to load new library data?.
        /// </summary>
        public static string ConfirmationBeforeErase_message {
            get {
                return ResourceManager.GetString("ConfirmationBeforeErase_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the entity, maybe it was deleted in the meantime by another user. Tha navigation is refreshed for you..
        /// </summary>
        public static string CouldNotLoadEntity_message {
            get {
                return ResourceManager.GetString("CouldNotLoadEntity_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup....
        /// </summary>
        public static string CreatingBackup_message {
            get {
                return ResourceManager.GetString("CreatingBackup_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string CultureInfo_constant {
            get {
                return ResourceManager.GetString("CultureInfo_constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hu-HU.
        /// </summary>
        public static string CultureInfoHun {
            get {
                return ResourceManager.GetString("CultureInfoHun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string CultureInfoUSeng {
            get {
                return ResourceManager.GetString("CultureInfoUSeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the data will be reloaded. Details:.
        /// </summary>
        public static string DataWillReloaded_message {
            get {
                return ResourceManager.GetString("DataWillReloaded_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46.84172812451524, 16.84248724161438.
        /// </summary>
        public static string DefaultCoordinates {
            get {
                return ResourceManager.GetString("DefaultCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description_colon {
            get {
                return ResourceManager.GetString("Description_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(id:{1}) didn&apos;t saved..
        /// </summary>
        public static string DidntSave_errorMessage {
            get {
                return ResourceManager.GetString("DidntSave_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard All.
        /// </summary>
        public static string DiscardAll {
            get {
                return ResourceManager.GetString("DiscardAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete {0}?.
        /// </summary>
        public static string DoYouReallyWantDelete_message {
            get {
                return ResourceManager.GetString("DoYouReallyWantDelete_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to backup database first before erase all photo data?.
        /// </summary>
        public static string DoYouWantBackup_message {
            get {
                return ResourceManager.GetString("DoYouWantBackup_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_menu {
            get {
                return ResourceManager.GetString("Edit_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has been changed in the meantime by someone else. Click OK to save your changes anyway, click Cancel to reload the entity from the database..
        /// </summary>
        public static string EntityHasBeenChanged_message {
            get {
                return ResourceManager.GetString("EntityHasBeenChanged_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has been deleted by another user.
        /// </summary>
        public static string EntityHasBeenDeleted_message {
            get {
                return ResourceManager.GetString("EntityHasBeenDeleted_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the entities,.
        /// </summary>
        public static string ErrorWhileSaveEntities_errorMessage {
            get {
                return ResourceManager.GetString("ErrorWhileSaveEntities_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend.
        /// </summary>
        public static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database has entry(s). Would you like to &apos;Extend&apos; existing or &apos;Overwrite&apos;?.
        /// </summary>
        public static string ExtendOrOverwrite_message {
            get {
                return ResourceManager.GetString("ExtendOrOverwrite_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File_menu {
            get {
                return ResourceManager.GetString("File_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be modified.
        /// </summary>
        public static string FileHasBeenModifiedFailed_message {
            get {
                return ResourceManager.GetString("FileHasBeenModifiedFailed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been succesfully modified.
        /// </summary>
        public static string FileHasBeenModifiedSucc_message {
            get {
                return ResourceManager.GetString("FileHasBeenModifiedSucc_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        public static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info_windowTitle {
            get {
                return ResourceManager.GetString("Info_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string Language_colon {
            get {
                return ResourceManager.GetString("Language_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the display language of the application. This change will take effect after restart..
        /// </summary>
        public static string LanguageSettingsDescription {
            get {
                return ResourceManager.GetString("LanguageSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Location_colon {
            get {
                return ResourceManager.GetString("Location_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location {0} can&apos;t be removed, as it is referenced by at least one photo.
        /// </summary>
        public static string LocationCantBeRemovedBecauseItIsUsedByEntity_message {
            get {
                return ResourceManager.GetString("LocationCantBeRemovedBecauseItIsUsedByEntity_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations_menu {
            get {
                return ResourceManager.GetString("Locations_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as unchanged.
        /// </summary>
        public static string MarkAsUnchanged {
            get {
                return ResourceManager.GetString("MarkAsUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Album.
        /// </summary>
        public static string NewAlbum_menu {
            get {
                return ResourceManager.GetString("NewAlbum_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new place.
        /// </summary>
        public static string NewPlace {
            get {
                return ResourceManager.GetString("NewPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_menu {
            get {
                return ResourceManager.GetString("Options_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size: .
        /// </summary>
        public static string PageSize_colon {
            get {
                return ResourceManager.GetString("PageSize_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page size determines how many photo will appear in navigation bar. Memory consumtion is lower in case of lower page size..
        /// </summary>
        public static string PageSizeSettingsDescription {
            get {
                return ResourceManager.GetString("PageSizeSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Path_colon {
            get {
                return ResourceManager.GetString("Path_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peoples:.
        /// </summary>
        public static string Peoples_colon {
            get {
                return ResourceManager.GetString("Peoples_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be deleted as it is part of at least one album..
        /// </summary>
        public static string PhotoCantDeleted_message {
            get {
                return ResourceManager.GetString("PhotoCantDeleted_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string PleaseWait_windowTitle {
            get {
                return ResourceManager.GetString("PleaseWait_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question_windowTitle {
            get {
                return ResourceManager.GetString("Question_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading files....
        /// </summary>
        public static string ReadingFiles_message {
            get {
                return ResourceManager.GetString("ReadingFiles_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Photo Library....
        /// </summary>
        public static string ReadPhotoLibrary_menu {
            get {
                return ResourceManager.GetString("ReadPhotoLibrary_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from shelve.
        /// </summary>
        public static string RemoveFromShelve {
            get {
                return ResourceManager.GetString("RemoveFromShelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All Tab.
        /// </summary>
        public static string SaveAllTab_menu {
            get {
                return ResourceManager.GetString("SaveAllTab_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As New.
        /// </summary>
        public static string SaveAsNew {
            get {
                return ResourceManager.GetString("SaveAsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Dialog.
        /// </summary>
        public static string SaveDialog_windowTitle {
            get {
                return ResourceManager.GetString("SaveDialog_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Existing.
        /// </summary>
        public static string SaveExisting {
            get {
                return ResourceManager.GetString("SaveExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save opened tabs before close?.
        /// </summary>
        public static string SaveWindowMessage {
            get {
                return ResourceManager.GetString("SaveWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a photo.
        /// </summary>
        public static string SelectPhoto_message {
            get {
                return ResourceManager.GetString("SelectPhoto_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a &apos;photo&apos; location:.
        /// </summary>
        public static string SelectPhotoLocation_message {
            get {
                return ResourceManager.GetString("SelectPhotoLocation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all.
        /// </summary>
        public static string SetAll {
            get {
                return ResourceManager.GetString("SetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Coordinate.
        /// </summary>
        public static string SetCoordinate {
            get {
                return ResourceManager.GetString("SetCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_menu {
            get {
                return ResourceManager.GetString("Settings_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelve.
        /// </summary>
        public static string Shelve {
            get {
                return ResourceManager.GetString("Shelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken Date:.
        /// </summary>
        public static string TakenDate_colon {
            get {
                return ResourceManager.GetString("TakenDate_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected path is invalid, would you like to try again?.
        /// </summary>
        public static string TheSelectedPathInvalid_message {
            get {
                return ResourceManager.GetString("TheSelectedPathInvalid_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Title_colon {
            get {
                return ResourceManager.GetString("Title_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred: {0}.
        /// </summary>
        public static string UnhandledExceptionOccurred_errorMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccurred_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning_windoTitle {
            get {
                return ResourceManager.GetString("Warning_windoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window_menu {
            get {
                return ResourceManager.GetString("Window_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write metadata.
        /// </summary>
        public static string WriteMetadata {
            get {
                return ResourceManager.GetString("WriteMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Saved Items Metadata.
        /// </summary>
        public static string WriteSavedItemsMetadata_menu {
            get {
                return ResourceManager.GetString("WriteSavedItemsMetadata_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing image metadata....
        /// </summary>
        public static string WritingMetadata_message {
            get {
                return ResourceManager.GetString("WritingMetadata_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing To File.
        /// </summary>
        public static string WritingToFileDialog_windowTitle {
            get {
                return ResourceManager.GetString("WritingToFileDialog_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
