// <auto-generated />
namespace PhotoOrganizer.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _1toNPhotoLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1toNPhotoLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "202103012239303_1toNPhotoLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
