// <auto-generated />
namespace PhotoOrganizer.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddAlbum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAlbum));
        
        string IMigrationMetadata.Id
        {
            get { return "202102081717530_AddAlbum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
